<a href="https://colab.research.google.com/github/gibranfp/CursoAprendizajeProfundo/blob/2026-1/notebooks/0a_tensores_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.researchgate.net/publication/349108714/figure/fig1/AS:988814684217344@1612763200002/Timeline-of-deep-learning-frameworks.png" alt="Historia de los marcos de trabajo de aprendizaje profundo" width="85%" height="30%"/>

Fuente: [https://www.researchgate.net/publication/349108714_DLBench_a_comprehensive_experimental_evaluation_of_deep_learning_frameworks](https://www.researchgate.net/publication/349108714_DLBench_a_comprehensive_experimental_evaluation_of_deep_learning_frameworks).

# Tensores
[PyTorch](https://pythorch.org/) es una biblioteca y marco de trabajo de código abierto que facilita la programación de redes neuronales profundas, ofreciendo varias funciones, clases y herramientas. En particular:

1. Definición de arreglos multidimensionales (clase `Tensor`) y operaciones entre ellos con soporte para GPUs y cómputo distribuido.
2. Diferenciación automática.
3. Interfaz modular con distintos niveles de abstracción para definir arquitecturas de redes neuronales y entrenarlas.
4. Clases y funciones para carga, generación de lotes y preprocesamiento de conjuntos de datos.

<img src="https://se.ewi.tudelft.nl/desosa2019/chapters/pytorch/images/pytorch/iGWbOXL.png" alt="Arquitectura de PyTorch" />

Fuente: [https://se.ewi.tudelft.nl/desosa2019/chapters/pytorch/](https://se.ewi.tudelft.nl/desosa2019/chapters/pytorch/)

In [1]:
import torch as th
import numpy as np

## Creación de tensores
El objeto básico de PyTorch es el tensor, un arreglo multidimensional similar al `ndarray` de NumPy.

![](https://static.packt-cdn.com/products/9781787125933/graphics/B07030_14_01.jpg)

Fuente: [Python Machine Learning - Second Edition](https://subscription.packtpub.com/book/big_data_and_business_intelligence/9781787125933/14/ch14lvl1sec85/tensorflow-ranks-and-tensors)

Podemos definir un tensor a partir de valores específicos con la función `tensor()`. Para un escalar (tensor de orden 0) esto sería:

In [2]:
escalar = th.tensor(4.0)
escalar, type(escalar)

(tensor(4.), torch.Tensor)

Un vector (tensor de orden 1):

In [3]:
vector = th.tensor([2.0, 3.0 , 4.0])
vector, type(vector)

(tensor([2., 3., 4.]), torch.Tensor)

Una matriz (tensor de orden 2):

In [4]:
matriz = th.tensor([[2.0, 3.0, 4.0], [5.0, 6.0, 7.0]])
matriz, type(matriz)

(tensor([[2., 3., 4.],
         [5., 6., 7.]]),
 torch.Tensor)

Un tensor de orden 3:

In [5]:
tensor3 = th.tensor([[[2.0, 3.0, 4.0], [5.0, 6.0, 7.0]], [[8.0, 9.0, 10.0], [11.0, 12.0, 13.0]]])
tensor3, type(tensor3)

(tensor([[[ 2.,  3.,  4.],
          [ 5.,  6.,  7.]],
 
         [[ 8.,  9., 10.],
          [11., 12., 13.]]]),
 torch.Tensor)

Similar a NumPy, las instancias de `Tensor` tienen varios atributos:

In [6]:
tensor3.dtype, tensor3.ndim, tensor3.shape, tensor3.size()

(torch.float32, 3, torch.Size([2, 2, 3]), torch.Size([2, 2, 3]))

PyTorch infiere el tipo de datos del tensor a partir de los valores, pero también es posible especificarlo.

In [7]:
tensor = th.tensor([1, 2, 3], dtype = th.float64)
tensor.dtype, tensor

(torch.float64, tensor([1., 2., 3.], dtype=torch.float64))

Otra forma de crear un tensor es con la función `zeros()`, que recibe como argumento la forma del tensor y regresa un tensor de esa forma con todos los elementos iguales a 0.

In [8]:
ceros = th.zeros((3, 4), dtype = th.float64)
ceros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)

Una variación de la función anterior es `zeros_like()`, la cual hace los mismo pero toma la forma a partir de tensor que se pasa como argumento.

In [9]:
ceros_l = th.zeros_like(ceros)
ceros_l

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)

La función `ones()` es similar a la función`zeros()` pero en lugar de poner todos los valores a 0 los pone a 1.

In [10]:
unos = th.ones((3, 4))
unos

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

De forma análoga, `ones_like()` es una variación de esta última función que toma la forma de otro tensor.

In [11]:
unos_l = th.ones_like(unos)
unos_l

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

PyTorch también permite crear tensores con valores muestreados de varias. Por ej. uniforme en un rango $[0,1)$ usando la función `rand`:

In [12]:
rnd = th.rand((3, 4))
rnd

tensor([[0.9398, 0.4413, 0.2003, 0.2301],
        [0.3915, 0.6604, 0.1474, 0.7093],
        [0.3186, 0.7849, 0.6382, 0.6130]])

Usando los tensores generados por `rand` (y `rand_like`) es posible generar tensores con valores muestreados de una uniforme en un rango $[a, b)$ de la siguiente manera:

In [13]:
a = -5
b = 3
unifab = th.rand((3, 4)) * (b - a) + a
unifab

tensor([[ 1.9082,  1.1394, -3.1635,  2.1847],
        [ 0.6637,  0.7308,  1.0902,  1.8762],
        [-2.5984, -0.4775,  2.4107, -3.0882]])

Alternativamente, podemos instanciar una clase `Tensor` pasando el tamaño como argumento al constructor y llamando al método `uniform_`

In [14]:
th.Tensor(3, 4).uniform_(-5, 3)

tensor([[ 2.6461,  1.8230, -3.2710, -0.2986],
        [-2.6093, -4.7255, -0.8285, -4.6658],
        [ 2.9231, -1.2227, -0.9234, -2.7613]])

Para valores enteros muestreados uniformemente tenemos la función `randint` (y `randint_like`).

In [15]:
randint = th.randint(low = -3, high = 5, size = (3, 4))
randint, th.randint_like(randint, low = -3, high=5)

(tensor([[ 0,  2, -2, -1],
         [ 3, -2, -2,  2],
         [ 0, -2,  1,  3]]),
 tensor([[ 4,  2,  2, -2],
         [-2,  4,  0,  2],
         [ 4, -2,  1,  0]]))

De forma similar, la función `randn` genera tensores con valores muestreados de una normal con media 0 y desviación estándar 1.

In [16]:
randn = th.randn((3,4))
randn

tensor([[ 0.9802,  0.1795,  0.7061, -1.9294],
        [-0.5715, -0.5061, -0.6036, -0.4219],
        [ 0.0654,  0.9324,  0.1490, -0.7669]])

Con los tensores generados por `randn` podemos generar tensores cuyos valores sean muestreados de una normal con distinta media y desviación estándar de la siguiente manera:

In [17]:
std = 10
mu = -5

randn2 = th.randn((3, 4)) * std + mu
randn2

tensor([[ -9.3161, -16.4924,   2.4005,  -8.4264],
        [-16.9877, -23.8938, -17.1483,  -2.8722],
        [ -4.5954,   0.4193,   2.8811,   7.9712]])

También podemos generar tensores con valores muestreados de una normal con media y desviación estándar arbitraria usando la función `normal`.

In [18]:
norm = th.normal(mean = -5, std = 10, size = (3, 4))
norm

tensor([[ -9.4871,  -0.9489,  -7.0473, -19.0269],
        [-20.8100,  -2.1623, -11.7830,   3.6316],
        [-13.1731,   6.4713, -11.0457,  -0.3412]])

Si deseamos generar tensores muestreados de una distribución multinomial podemos usar la función `multinomial`, a la cual deben especificarse las probabilidades de cada clase como un tensor de orden 1 y el número de muestras.

In [19]:
multi = th.multinomial(th.tensor([0.1, 0.2, 0.7]), num_samples = 100, replacement=True)
multi

tensor([1, 2, 2, 0, 2, 1, 2, 2, 1, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
        2, 2, 2, 2, 2, 0, 0, 2, 1, 2, 0, 2, 2, 0, 1, 2, 0, 2, 2, 0, 1, 0, 2, 2,
        0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 0, 2, 2, 1, 2,
        2, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2,
        1, 2, 2, 2])

El número de clases depende del tamaño del tensor y el argumento `replacemente` define si las muestras son con o sin reemplazo (en este último caso el número de muestras debe ser menor o igual al número de clases).

Por otra parte, la función `arange()` genera una secuencia de números (como el `range()` de Python):

In [20]:
rango = th.arange(start=-3, end = 5, step = 0.5)
rango

tensor([-3.0000, -2.5000, -2.0000, -1.5000, -1.0000, -0.5000,  0.0000,  0.5000,
         1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000])

De manera similar, la función `linspace()` genera tensores con valores con el mismo espaciados en un intervalo.



In [21]:
ls = th.linspace(start = -3, end = 5, steps = 20)
ls

tensor([-3.0000, -2.5789, -2.1579, -1.7368, -1.3158, -0.8947, -0.4737, -0.0526,
         0.3684,  0.7895,  1.2105,  1.6316,  2.0526,  2.4737,  2.8947,  3.3158,
         3.7368,  4.1579,  4.5789,  5.0000])

## Tipos

Los elementos de los tensores pueden ser de distintos tipos básicos y precisiones. Por ej. flotantes de 16 bits (`float16`) o enteros sin signo de 8 bits (`uint8`).

![](https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-020-2649-2/MediaObjects/41586_2020_2649_Fig1_HTML.png)

Fuente: [Array programming with NumPy](https://www.nature.com/articles/s41586-020-2649-2).


In [22]:
ten16 = th.randn((3, 4), dtype = th.float16)
ten16

tensor([[-2.1660,  1.6943,  0.1114, -0.7046],
        [-0.6001, -1.0869, -0.0910, -0.0566],
        [ 0.7119,  1.5508, -0.8315, -0.8315]], dtype=torch.float16)

También se pueden convertir de tipos con el método `type()`:

In [23]:
ten64 = ten16.type(th.float64)
ten64, ten16

(tensor([[-2.1660,  1.6943,  0.1114, -0.7046],
         [-0.6001, -1.0869, -0.0910, -0.0566],
         [ 0.7119,  1.5508, -0.8315, -0.8315]], dtype=torch.float64),
 tensor([[-2.1660,  1.6943,  0.1114, -0.7046],
         [-0.6001, -1.0869, -0.0910, -0.0566],
         [ 0.7119,  1.5508, -0.8315, -0.8315]], dtype=torch.float16))

## Índices
Los índices de los tensores siguen reglas similares a los arreglos de NumPy y las listas de Python.

In [24]:
randint

tensor([[ 0,  2, -2, -1],
        [ 3, -2, -2,  2],
        [ 0, -2,  1,  3]])

In [25]:
randint[1:, 1]

tensor([-2, -2])

También se pueden realizar _slices_:

In [26]:
randint[1, ::2]

tensor([ 3, -2])

A diferencia de los arreglos de NumPy, en las instancias de `Tensor` no es posible que el paso de los índices sea negativo.

In [27]:
# randint[1][::-1]

Ademas, podemos iterar sobre los elementos de un tensor:

In [28]:
for x in randint:
  print(x)

for x in randint:
  for e in x:
    print(e)

tensor([ 0,  2, -2, -1])
tensor([ 3, -2, -2,  2])
tensor([ 0, -2,  1,  3])
tensor(0)
tensor(2)
tensor(-2)
tensor(-1)
tensor(3)
tensor(-2)
tensor(-2)
tensor(2)
tensor(0)
tensor(-2)
tensor(1)
tensor(3)


## Formas
La forma de los tensores pueden cambiar, siempre y cuando se mantenga el mismo número de elementos totales:

![](https://www.tensorflow.org/guide/images/tensor/reshape-before.png)
![](https://www.tensorflow.org/guide/images/tensor/reshape-good1.png)
![](https://www.tensorflow.org/guide/images/tensor/reshape-good2.png)

Fuente: Tutorial [_Introduction to Tensors_](https://www.tensorflow.org/guide/tensor) de Tensorflow

In [29]:
x_orig = th.arange(30)
x_orig

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

Nota que es necesario asegurarse de que, al cambiar la forma, el número total de elementos sea el mismo. Por ej. si tenemos 30 elementos, solo podemos cambiar a formas en las que el producto de todas las dimensiones sea igual a 30 ($5 \times 6$, $6 \times 5$, $3 \times 10$, $10 \times 3$, $1 \times 30$, $30 \times 1$, $1 \times 1 \times 30$, $5 \times 1 \times 6$, etc.).

Para cambiar la forma de este vector usamos la función (o el método) `reshape()`.

In [30]:
x_forma2 = th.reshape(x_orig, [6, 5])
x_forma3 = th.reshape(x_orig, [3, 10])
x_forma4 = th.reshape(x_orig, [2, 3, 5])
x_forma5 = th.reshape(x_orig, [5, 3, 2])

Examinemos sus formas:

In [31]:
x_forma2.shape, x_forma3.shape, x_forma4.shape, x_forma5.shape

(torch.Size([6, 5]),
 torch.Size([3, 10]),
 torch.Size([2, 3, 5]),
 torch.Size([5, 3, 2]))

In [32]:
x_forma2, x_orig

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]),
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))

In [33]:
x_forma2[0, 1] = 0
x_forma2, x_orig

(tensor([[ 0,  0,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]),
 tensor([ 0,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]))

Si solo requerimos agregar una dimensión, además de la función `reshape` podemos usar `unsqueeze`, la cual toma como argumento un tensor y un eje y regresa un tensor con los mismos elementos pero con una dimensión agregada.

In [34]:
x_forma_usq = th.unsqueeze(x_forma3, dim = 1)
x_forma_usq.shape

torch.Size([3, 1, 10])

Para quitar dimensiones de tamaño 1 se puede utilizar la función `squeeze`.

In [35]:
th.squeeze(x_forma_usq).shape

torch.Size([3, 10])

Cuando redimensionamos con `reshape` o asignamos un tensor a otro, no se está creando una copia del tensor original en memoria, sino que solo se modifica la cabecera.

In [36]:
x_orig2 = x_orig
x_orig2[5] = 1000
x_orig, x_orig2, x_forma2, x_forma3

(tensor([   0,    0,    2,    3,    4, 1000,    6,    7,    8,    9,   10,   11,
           12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
           24,   25,   26,   27,   28,   29]),
 tensor([   0,    0,    2,    3,    4, 1000,    6,    7,    8,    9,   10,   11,
           12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
           24,   25,   26,   27,   28,   29]),
 tensor([[   0,    0,    2,    3,    4],
         [1000,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19],
         [  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29]]),
 tensor([[   0,    0,    2,    3,    4, 1000,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
         [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29]]))

Para crear una copia de los datos es necesario usar el método `clone()` o `deepcopy()`.

In [37]:
x_orig_clone = x_orig.clone()
x_orig[3] = -1
x_orig, x_orig_clone

(tensor([   0,    0,    2,   -1,    4, 1000,    6,    7,    8,    9,   10,   11,
           12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
           24,   25,   26,   27,   28,   29]),
 tensor([   0,    0,    2,    3,    4, 1000,    6,    7,    8,    9,   10,   11,
           12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
           24,   25,   26,   27,   28,   29]))

## PyTorch y NumPy
Los tensores de PyTorch se pueden convertir a arreglos de NumPy y viceversa.

In [38]:
nparr = np.ones((2, 5))

De arreglo de NumPy a Tensorflow:

In [39]:
tharr = th.tensor(nparr)

De tensor a arreglo de NumPy con método `numpy` de cualquier instancia de `Tensor`.

In [40]:
tharr.numpy()

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Operaciones básicas
PyTorch cuenta con operadores y funciones básicas para los tensores, similares a las de NumPy, entre ellas operadores elemento a elemento, multiplicación de tensores, etc.

### Elemento a elemento
Estas operaciones se realizan entre dos tensores que tienen la misma forma. El resultado es un tensor con la misma forma que la de los operandos, cuyos elementos se obtienen al aplicar la operación especificada entre cada elemento de un tensor y el correspondiente elemento del otro tensor. Estas operaciones pueden ser suma, resta, división, multiplicación, potenciación, etc.

In [41]:
x = th.tensor([1., 2., 3.])
y = th.tensor([3., 4., 5.])

x, y

(tensor([1., 2., 3.]), tensor([3., 4., 5.]))

In [42]:
10 * x, x + y, x - y, x * y, x / y, x**y, x**2

(tensor([10., 20., 30.]),
 tensor([4., 6., 8.]),
 tensor([-2., -2., -2.]),
 tensor([ 3.,  8., 15.]),
 tensor([0.3333, 0.5000, 0.6000]),
 tensor([  1.,  16., 243.]),
 tensor([1., 4., 9.]))

In [43]:
a = th.reshape(th.arange(4), [4, 1])
b = th.arange(2).reshape(1, 2)

a, b, a * b

(tensor([[0],
         [1],
         [2],
         [3]]),
 tensor([[0, 1]]),
 tensor([[0, 0],
         [0, 1],
         [0, 2],
         [0, 3]]))

### Transpuesta, producto y concatenación
Es posible obtener la transpuesta de una matriz usando la función `transpose` (como argumentos se ponen los índices de los ejes en el orden deseado) o el método `.T` de cualquier instancia de `Tensor`. Además, podemos calcular el producto de dos vectores, dos matrices o un vector y una matriz.

In [44]:
x = x.reshape(1, 3)
th.transpose(x, 1, 0), x.T

(tensor([[1.],
         [2.],
         [3.]]),
 tensor([[1.],
         [2.],
         [3.]]))

In [45]:
M1 = th.rand((4,3))
M2 = th.rand((3, 2))

M1.T.shape, M2.T.shape

(torch.Size([3, 4]), torch.Size([2, 3]))

In [46]:
M1 @ M2, th.matmul(M1, M2), M1 @ x.T

(tensor([[0.6377, 1.1162],
         [1.1252, 1.1334],
         [0.9953, 1.2731],
         [0.6751, 0.8980]]),
 tensor([[0.6377, 1.1162],
         [1.1252, 1.1334],
         [0.9953, 1.2731],
         [0.6751, 0.8980]]),
 tensor([[2.5446],
         [3.0449],
         [3.4726],
         [1.8247]]))

También podemos concatenar (función `concat`) una lista de tensores (primer argumento) sobre un eje específico (argumento `axis`).

In [47]:
th.concat([M1, M2.T], axis = 0), th.concat([M1.T, M2], axis = 1)

(tensor([[0.2375, 0.9145, 0.1593],
         [0.9897, 0.0967, 0.6206],
         [0.4891, 0.6718, 0.5466],
         [0.6905, 0.3373, 0.1532],
         [0.6073, 0.4033, 0.7818],
         [0.7244, 0.9410, 0.5244]]),
 tensor([[0.2375, 0.9897, 0.4891, 0.6905, 0.6073, 0.7244],
         [0.9145, 0.0967, 0.6718, 0.3373, 0.4033, 0.9410],
         [0.1593, 0.6206, 0.5466, 0.1532, 0.7818, 0.5244]]))

De forma similar, es posible apilar tensores sobre un eje usando la función `stack` (el tensor resultando es un orden mayor al de los tensores de argumento, los cuales tienen la misma forma).

In [48]:
M1 = th.rand((2,3))
M2 = th.rand((2,3))
M3 = th.rand((2,3))
M4 = th.rand((2,3))
th.stack([M1, M2, M3, M4], axis = 0).shape, th.stack([M1, M2, M3, M4], axis = 1).shape, th.stack([M1, M2, M3, M4], axis = 2).shape

(torch.Size([4, 2, 3]), torch.Size([2, 4, 3]), torch.Size([2, 3, 4]))

## Reducción
También se puede reducir un eje de un tensor con distintas funciones (y métodos equivalentes), tales como suma (`sum`), producto (`prod`) y promedio (`mean`):

In [49]:
x_red = th.rand([3, 10])

x_red, th.max(x_red), x_red.min(), x_red.argmax(), x_red.argmin(), x_red.sum(), x_red.prod(), x_red.mean()

(tensor([[0.9784, 0.2644, 0.5512, 0.5452, 0.9617, 0.4336, 0.8368, 0.1646, 0.4565,
          0.6410],
         [0.7228, 0.5353, 0.0247, 0.6202, 0.3383, 0.9066, 0.1115, 0.9543, 0.0234,
          0.5380],
         [0.3215, 0.4757, 0.3661, 0.9893, 0.7417, 0.1102, 0.5952, 0.9234, 0.5171,
          0.9197]]),
 tensor(0.9893),
 tensor(0.0234),
 tensor(23),
 tensor(18),
 tensor(16.5685),
 tensor(3.7654e-12),
 tensor(0.5523))

Es posible especificar un eje donde se desea realizar la reducción, para las funciones/métodos `min` y `max` devuelven un par de tensores: el primero es el de valores mínimos y el segundo es el de los índices de estos valores.

In [50]:
x_red.max(axis = 0)

torch.return_types.max(
values=tensor([0.9784, 0.5353, 0.5512, 0.9893, 0.9617, 0.9066, 0.8368, 0.9543, 0.5171,
        0.9197]),
indices=tensor([0, 1, 0, 2, 0, 1, 0, 1, 2, 2]))

Para el eje 1 del mismo tensor:

In [51]:
x_red.mean(axis = 1)

tensor([0.5833, 0.4775, 0.5960])

Por otro lado, tenemos la función (y el método) `sort` que ordena un tensor. Al igual que `min` y `max`, cuando se especifica un eje `sort` regresa tanto el tensor de valores como el tensor de índices. Si solo requerimos los índices, podemos usar la función `argsort`.

In [52]:
xsort = th.randint(low = -10, high = 10, size = (3, 4))
th.sort(xsort, descending = True), th.sort(xsort, descending = False), th.sort(xsort, descending = False, axis = 0)

(torch.return_types.sort(
 values=tensor([[ 1, -1, -4, -8],
         [ 7,  3,  2,  1],
         [ 5,  0, -2, -3]]),
 indices=tensor([[1, 0, 3, 2],
         [2, 1, 3, 0],
         [2, 3, 0, 1]])),
 torch.return_types.sort(
 values=tensor([[-8, -4, -1,  1],
         [ 1,  2,  3,  7],
         [-3, -2,  0,  5]]),
 indices=tensor([[2, 3, 0, 1],
         [0, 3, 1, 2],
         [1, 0, 3, 2]])),
 torch.return_types.sort(
 values=tensor([[-2, -3, -8, -4],
         [-1,  1,  5,  0],
         [ 1,  3,  7,  2]]),
 indices=tensor([[2, 2, 0, 0],
         [0, 0, 2, 2],
         [1, 1, 1, 1]])))

## GPUs
En muchos casos, el uso de GPUs reduce significativamente el tiempo de entrenamiento de los modelos basados en redes neuronales profundas. Por lo mismo, los marcos de trabajo como PyTorch permiten crear o copiar tensores y ejecutar las operaciones tensoriales en uno o más CPUs/GPUs e incluso en distintas computadoras. Además, ofrecen herramientas para controlar de manera flexible dónde se crea o copia cada tensor y dónde se ejecuta cada operación. Por ello, cada instancia de la clase `Tensor` cuenta con el elemento `.device` que indica el dispositivo en el que se encuentra almacenado. Por defecto, si hay al menos uno disponible, los tensores se crean en el GPU.

In [53]:
!nvidia-smi

Thu Aug 14 17:25:43 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [54]:
xcpu = th.rand((100, 100))
xcpu.device

device(type='cpu')

Podemos especificar explícitamente dónde queremos crear una instancia de `Tensor` usando el argumento `device` que tienen muchas funciones de PyTorch. Por ej. si queremos crear el tensor en GPU pasamos la cadena `cuda` o `cuda:0`, donde el valor después de los dos puntos en esta última forma especifica el índice del GPU (es distinto de 0 cuando tenemos múltiples GPUs disponibles).

In [55]:
xgpu = th.rand((100, 100), device = 'cuda:0')
xgpu.device

device(type='cuda', index=0)

Las operaciones que se realicen con estos tensores se correrán en el GPU y los tensores resultantes estarán en este mismo dispositivo.

In [56]:
ygpu = th.rand((100, 100), device = 'cuda:0')
(xgpu + ygpu).device

device(type='cuda', index=0)

Sin embargo, cuando realizamos una operación con tensores que se encuentran en dispositivos distintos, PyTorch lanza un error.!)

In [57]:
xgpu + xcpu

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Por lo tanto, para poder realizar esta operación es necesario transferir uno de los tensores a otro dispositivo. En PyTorch esto lo llevamos a cabo con el método `to`.

In [58]:
xcpugpu = xcpu.to('cuda:0')
(xcpugpu + xgpu).device, xcpugpu.device

(device(type='cuda', index=0), device(type='cuda', index=0))

Para saber si algún GPU está disponible, contamos con la función `is_available` del módulo de `cuda`.

In [59]:
th.cuda.is_available()

True

Comparémos ahora los tiempos de ejecución en CPU y GPU de una multiplicación de dos matrices.

In [60]:
%%timeit -n1 -r1
disp = 'cpu'
res = th.rand((10000, 10000), device = disp) @ th.rand((10000, 10000), device = disp)

36.5 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [61]:
%%timeit -n1 -r1
disp = 'cuda:0'
res = th.rand((10000, 10000), device = disp) @ th.rand((10000, 10000), device = disp)

156 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


### Ejercicio
Calcula y despliega el producto de cada matriz de $400 \times 1000$ en un tensor aleatorio $A$ de tamaño $500 \times 400 \times 1000$ con la transpuesta de un tensor aleatorio $B$ de tamaño $200 \times 1000$. Concatena el resultado a un tensor aleatorio $C$ con el mismo número de columnas que el resultado de la operación anterior. Compara los tiempos de ejecución de esta operación en GPU y CPU.