<a href="https://colab.research.google.com/github/gibranfp/CursoAprendizajeProfundo/blob/2026-1/notebooks/3a_celda_recurrente.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.random.seed(123)
from collections import Counter

textos = ['ya casi termina el mes',
          'ya hay pan de muerto']
n_docs = len(textos)

In [2]:
tokens = [t.split() for t in textos]
max_sec = len(tokens[0])
print(tokens[0])
print(tokens[1])

['ya', 'casi', 'termina', 'el', 'mes']
['ya', 'hay', 'pan', 'de', 'muerto']


In [3]:
voc = Counter([p for t in tokens for p in t])

i2p = {i:p for i,(p,f) in enumerate(voc.most_common())}
p2i = {p:i for i,(p,f) in enumerate(voc.most_common())}

tam_voc = len(i2p)

indsecs = np.array([[p2i[p] for p in t] for t in tokens])

print(tam_voc)
print(indsecs)

9
[[0 1 2 3 4]
 [0 5 6 7 8]]


In [4]:
ohesecs = np.zeros((n_docs, max_sec, tam_voc))

for i in range(ohesecs.shape[0]):
  for j in range(ohesecs.shape[1]):
    ohesecs[i, j, indsecs[i, j]] = 1

print(ohesecs)

[[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0.]]

 [[1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1.]]]


In [5]:
tam_edo = 10

h = np.zeros((tam_edo, 1))

k = 1 / tam_edo
Wih = np.random.uniform(-np.sqrt(k), np.sqrt(k), size=(tam_voc, tam_edo))
Whh = np.random.uniform(-np.sqrt(k), np.sqrt(k), size=(tam_edo, tam_edo))
b = np.random.uniform(-np.sqrt(k), np.sqrt(k), size=(tam_edo, 1))

print(Wih)
print(Whh)
print(b)
print(h)

[[ 0.12425802 -0.13525736 -0.17275431  0.03245431  0.13880436 -0.04863174
   0.30406198  0.11689659 -0.01205972 -0.06823087]
 [-0.09918293  0.14486375 -0.03885032 -0.27848415 -0.06448247  0.15052151
  -0.20080986 -0.20526233  0.01995484  0.02012953]
 [ 0.08500263  0.22100007  0.14195801  0.07021743  0.14068555 -0.11197061
  -0.08741253 -0.17186142 -0.13046669  0.08283657]
 [-0.25797549 -0.04193106 -0.04372623 -0.00399389 -0.04690904 -0.11873643
  -0.04657952  0.24880115  0.28091146  0.00116162]
 [ 0.07839473 -0.24310427 -0.11555881 -0.05386863  0.23167425 -0.15782588
  -0.01073007  0.30709497  0.01232347  0.07140077]
 [-0.2399355   0.20639604  0.06518095  0.02850351 -0.09944488 -0.12388489
  -0.05247976  0.11466467  0.23745976  0.00659166]
 [ 0.10708344  0.05435105  0.07899591  0.11048306  0.21651637 -0.26361064
   0.16676767 -0.16211962 -0.19339038  0.0458258 ]
 [-0.25569386  0.24370208  0.08047932  0.14130091 -0.30602676  0.05972396
   0.03591411 -0.21569286 -0.21941747  0.12366373]


In [6]:
print(h)

x = ohesecs[0, 0].reshape(-1, 1)
h = np.tanh(Wih.T @ x + Whh.T @ h + b)

print(x)
print(h)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[-0.06154547]
 [ 0.00246461]
 [-0.24425149]
 [ 0.13806229]
 [-0.15755648]
 [ 0.03730187]
 [ 0.00819779]
 [ 0.26521478]
 [-0.02918276]
 [-0.29811952]]


In [7]:
x = ohesecs[0, 1].reshape(-1, 1)
h = np.tanh(Wih.T @ x + Whh.T @ h + b)

print(h)

[[-0.28251876]
 [ 0.39224025]
 [-0.01807492]
 [-0.38168506]
 [-0.32930351]
 [ 0.30124444]
 [-0.40439839]
 [ 0.045301  ]
 [ 0.09017754]
 [-0.2881811 ]]


In [8]:
x = ohesecs[0, 2].reshape(-1, 1)
h = np.tanh(Wih.T @ x + Whh.T @ h + b)

print(h)

[[-0.26262172]
 [ 0.37673501]
 [ 0.23468891]
 [-0.03425512]
 [-0.40740165]
 [ 0.02946663]
 [-0.09695202]
 [-0.14203018]
 [-0.15789488]
 [-0.08409326]]


In [9]:
x = ohesecs[0, 3].reshape(-1, 1)
h = np.tanh(Wih.T @ x +  Whh.T @ h + b)

print(h)

[[-0.52286184]
 [ 0.14157893]
 [-0.25929135]
 [-0.07301653]
 [-0.54924991]
 [ 0.1001888 ]
 [-0.08932687]
 [ 0.44125724]
 [ 0.27284658]
 [-0.16888303]]


In [10]:
x = ohesecs[0, 4].reshape(-1, 1)
h = np.tanh(Wih.T @ ohesecs[0, 4].reshape(-1, 1) + Whh.T @ h + b)

print(h)

[[-2.26399327e-01]
 [-8.59612329e-02]
 [ 1.89970050e-04]
 [-3.16342120e-01]
 [-1.85474053e-01]
 [ 2.32991250e-02]
 [-1.93538688e-01]
 [ 5.35019425e-01]
 [ 2.02901022e-01]
 [-1.92052934e-01]]


In [11]:
class CeldaRecurrente:
  def __init__(self, tam_ent, tam_edo):
    self.input_size = tam_ent
    self.hidden_size = tam_edo

    k = 1 / tam_edo
    self.W = np.random.uniform(-np.sqrt(k), np.sqrt(k),
                               size=(tam_edo + tam_voc, tam_edo))
    self.b = np.random.uniform(-np.sqrt(k), np.sqrt(k),
                               size=(tam_edo, 1))

  def __call__(self, x, h):
    xh = np.concatenate((x.reshape(-1, 1), h), axis=0)
    return np.tanh(self.W.T @ xh + self.b)

In [12]:
def ejecuta_celda(celda, X, h0):
  # Calculamos los estados para todas las entradas
  # del primer ejemplo
  for i in range(X.shape[0]):
    print(f'Ejemplo {i}')
    h = h0 # primer estado con ceros
    print(f'\tEstado 0: {h.reshape(-1)}')
    for t in range(X.shape[1]):
      print(f'\tEntrada {t}: {X[i, t]}')
      h = celda(X[i, t], h)
      print(f'\tEstado {t + 1}: {h.reshape(-1)}')

rec = CeldaRecurrente(tam_voc, tam_edo)
ejecuta_celda(rec, ohesecs, np.zeros((tam_edo, 1)))

Ejemplo 0
	Estado 0: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
	Entrada 0: [1. 0. 0. 0. 0. 0. 0. 0. 0.]
	Estado 1: [-0.22980248 -0.35477119  0.36100229  0.2987813   0.02502332 -0.04159293
 -0.40892099  0.07639954 -0.07625024 -0.06640506]
	Entrada 1: [0. 1. 0. 0. 0. 0. 0. 0. 0.]
	Estado 2: [-0.10688934 -0.3065553   0.41428777  0.16063938 -0.11324161 -0.07182619
 -0.31246449  0.04248702 -0.05453518  0.20992951]
	Entrada 2: [0. 0. 1. 0. 0. 0. 0. 0. 0.]
	Estado 3: [-0.34102884  0.09514627  0.25391891  0.29088904  0.24073893 -0.29534944
 -0.11941504  0.18016119 -0.3193917   0.00126602]
	Entrada 3: [0. 0. 0. 1. 0. 0. 0. 0. 0.]
	Estado 4: [-0.58108759 -0.46051105  0.28022796 -0.03755576  0.03858157 -0.25651351
 -0.39273831  0.38844776 -0.28836536  0.31325888]
	Entrada 4: [0. 0. 0. 0. 1. 0. 0. 0. 0.]
	Estado 5: [-0.53245826 -0.42190573  0.72120953 -0.139595   -0.12830557 -0.15437957
  0.10778412 -0.05507797  0.05366813  0.39281483]
Ejemplo 1
	Estado 0: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
	Entrada 0: [1. 0. 

In [13]:
class CeldaRecurrenteSep:
  def __init__(self, tam_ent, tam_edo):
    self.input_size = tam_ent
    self.hidden_size = tam_edo

    k = 1 / tam_edo
    self.Wih = np.random.uniform(-np.sqrt(k), np.sqrt(k),
                                 size=(tam_voc, tam_edo))
    self.Whh = np.random.uniform(-np.sqrt(k), np.sqrt(k),
                                 size=(tam_edo, tam_edo))
    self.b = np.random.uniform(-np.sqrt(k), np.sqrt(k),
                               size=(tam_edo, 1))

  def __call__(self, x, h):
    x = x.reshape(-1, 1)
    return np.tanh(self.Wih.T @ x + self.Whh @ h + self.b)

recsep = CeldaRecurrenteSep(tam_voc, tam_edo)
ejecuta_celda(recsep, ohesecs, np.zeros((tam_edo, 1)))

Ejemplo 0
	Estado 0: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
	Entrada 0: [1. 0. 0. 0. 0. 0. 0. 0. 0.]
	Estado 1: [-0.04965837 -0.17845274  0.20916877 -0.34220176  0.26863095 -0.31200335
  0.23013283  0.02105898 -0.32218725 -0.52938904]
	Entrada 1: [0. 1. 0. 0. 0. 0. 0. 0. 0.]
	Estado 2: [-0.41442375 -0.03518597  0.24433459 -0.13605271 -0.09972991 -0.1980722
 -0.1699397  -0.17288954 -0.65192553 -0.1436782 ]
	Entrada 2: [0. 0. 1. 0. 0. 0. 0. 0. 0.]
	Estado 3: [-7.31805616e-02 -1.72479804e-01  2.15804450e-01  2.67634476e-02
 -3.19360090e-04  2.66969216e-01  4.36093580e-01 -7.53599456e-02
 -4.93048535e-01 -4.44544910e-01]
	Entrada 3: [0. 0. 0. 1. 0. 0. 0. 0. 0.]
	Estado 4: [-0.0592631  -0.36711581 -0.18995557 -0.4842966  -0.30367831 -0.22048798
  0.45813414 -0.32575902 -0.35242498 -0.42336638]
	Entrada 4: [0. 0. 0. 0. 1. 0. 0. 0. 0.]
	Estado 5: [-0.14343842 -0.16706511  0.02660835 -0.33119703 -0.45381393  0.17178328
  0.33346002 -0.24261742 -0.5572012  -0.70962069]
Ejemplo 1
	Estado 0: [0. 0. 0. 0

In [14]:
import torch as th

recth = th.nn.RNNCell(tam_voc, tam_edo)
oheth = th.from_numpy(ohesecs).type(th.float32)

ejecuta_celda(recth, oheth, th.zeros((tam_edo)))

Ejemplo 0
	Estado 0: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
	Entrada 0: tensor([1., 0., 0., 0., 0., 0., 0., 0., 0.])
	Estado 1: tensor([-0.4274, -0.2229,  0.0142,  0.1874,  0.0408, -0.1061,  0.5410,  0.5143,
         0.1529,  0.0056], grad_fn=<ViewBackward0>)
	Entrada 1: tensor([0., 1., 0., 0., 0., 0., 0., 0., 0.])
	Estado 2: tensor([-0.6255,  0.3047,  0.0506, -0.2944, -0.0412, -0.0972,  0.1289,  0.5895,
         0.0331, -0.3412], grad_fn=<ViewBackward0>)
	Entrada 2: tensor([0., 0., 1., 0., 0., 0., 0., 0., 0.])
	Estado 3: tensor([-0.6903, -0.0709,  0.3260,  0.3120, -0.4266, -0.2746,  0.3965,  0.3378,
         0.3503,  0.0244], grad_fn=<ViewBackward0>)
	Entrada 3: tensor([0., 0., 0., 1., 0., 0., 0., 0., 0.])
	Estado 4: tensor([-0.5659,  0.3729,  0.1600, -0.0055, -0.3031, -0.0401,  0.6338,  0.3734,
         0.0674, -0.2987], grad_fn=<ViewBackward0>)
	Entrada 4: tensor([0., 0., 0., 0., 1., 0., 0., 0., 0.])
	Estado 5: tensor([-0.3879,  0.2766,  0.3993,  0.2409, -0.3787,  0.1628, 

In [15]:
rnn = th.nn.RNN(tam_voc, tam_edo) # Interfaz de más alto nivel que RNNCell.
                                  # puede procesar varios pasos y ejemplos
                                  # a la vez. Además, se pueden definir celdas
                                  # apiladas y bidireccionales
outputs, h = rnn(oheth)

In [16]:
lstm = th.nn.LSTM(tam_voc, tam_edo, batch_first=True) # Similar a la anterior
                                                      # para celda LSTM
output, (h,c) = lstm(oheth)

In [17]:
gru = th.nn.GRU(tam_voc, tam_edo, batch_first=True) # Similar a la anterior
                                                    # para celda GRU
output, h = gru(oheth)

In [18]:
outputs

tensor([[[ 3.5648e-01,  9.8299e-02, -1.8170e-01,  4.0193e-01, -2.7771e-01,
           2.8259e-01,  2.1574e-01, -2.5180e-01,  4.2298e-01,  3.2511e-01],
         [ 3.0244e-01,  3.8079e-01, -4.6111e-01,  3.0158e-01, -2.1777e-01,
          -1.3020e-01,  1.3940e-01, -9.0547e-02,  1.4396e-01, -1.6936e-01],
         [ 2.8661e-01,  4.0837e-01, -6.2895e-01,  1.8743e-01,  3.0115e-05,
          -8.6065e-02,  1.4770e-01,  9.4007e-02,  4.2768e-01,  2.0527e-01],
         [ 1.6595e-01,  4.1689e-01, -4.7317e-01,  1.8047e-01,  8.4342e-02,
           3.0388e-01,  2.7167e-02,  3.3396e-01,  2.2793e-01,  2.5023e-01],
         [ 3.0759e-01,  1.6118e-01, -5.7096e-01,  4.1849e-01, -1.6899e-01,
           2.9504e-01,  3.4513e-02, -6.0280e-02,  5.7209e-01,  3.6703e-01]],

        [[ 2.9808e-01,  1.3058e-01, -1.9681e-01,  5.7934e-01, -2.1289e-01,
           3.0763e-01,  1.0848e-01, -4.0973e-01,  1.7761e-01,  2.5220e-01],
         [-2.3995e-01,  1.8160e-01, -2.4028e-01,  4.9986e-01,  2.6868e-01,
           2.2228